development:
  cloud_name: dsoaq1rmb
  api_key: '144599123285664'
  api_secret: 'b2lRFejWICIsiOZGGNtiese_Kfo'
production:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_file_support: true
  secure: true
test:
  cloud_name: dsoaq1rmb
  api_key: '144599123285664'
  api_secret: "b2lRFejWICIsiOZGGNtiese_Kfo"
  enhance_image_tag: true
  static_file_support: false